// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var NoCaptcha, exports, https, querystring, _;

  _ = require('underscore');

  https = require('https');

  querystring = require('querystring');

  module.exports = exports = NoCaptcha = (function() {
    function NoCaptcha(publicKey, privateKey, isSecure) {
      this.PUBLIC_KEY = publicKey;
      this.PRIVATE_KEY = privateKey;
      this.IS_SECURE = (isSecure != null) === true;
    }

    NoCaptcha.prototype.toHTML = function(options) {
      var div, external, script, script_src;
      script_src = "www.google.com/recaptcha/api.js";
      script_src = (this.IS_SECURE ? 'https://' : 'http://') + script_src;
      div = "<div class='g-recaptcha' data-sitekey='" + this.PUBLIC_KEY + "'";
      if (options != null) {
        external = querystring.stringify(_.pick(options, ['onload', 'render', 'hl']));
        script_src = script_src + '?' + external;
        if (options.theme === 'dark' || options.theme === 'light') {
          div = div + (" data-theme='" + options.theme + "'");
        }
        if (options.type === 'audio' || options.type === 'image') {
          div = div + (" data-type='" + options.type + "'");
        }
        if (options.callback) {
          div = div + (" data-callback='" + options.callback + "'");
        }
      }
      div = div + "></div>";
      script = "<script src='" + script_src + "' async defer></script>";
      return script + div;
    };

    NoCaptcha.prototype.verify = function(_arg, callback) {
      var external, remoteip, reqOption, request, response;
      response = _arg.response, remoteip = _arg.remoteip;
      if (!callback) {
        return new Error('No callback');
      }
      if (response == null) {
        return callback(new Error('No response'));
      }
      if (remoteip == null) {
        return callback(new Error('No remote IP'));
      }
      external = querystring.stringify({
        secret: this.PRIVATE_KEY,
        response: response,
        remoteip: remoteip
      });
      reqOption = {
        host: 'www.google.com',
        path: '/recaptcha/api/siteverify?' + external,
        port: 443
      };
      return request = https.get("https://www.google.com/recaptcha/api/siteverify?" + external, function(resp) {
        var data;
        data = '';
        resp.on('data', function(chunk) {
          return data += chunk;
        });
        return resp.on('end', function() {
          var res;
          res = JSON.parse(data);
          if (res.success === true) {
            return callback(null, res);
          } else {
            return callback(new Error(res['error-codes'] || "Invalide response"));
          }
        });
      }).on('error', function(err) {
        return callback(err);
      });
    };

    return NoCaptcha;

  })();

}).call(this);
